services:
  inventory-db:
    image: postgres:15-alpine
    container_name: inventory-postgres-dev
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - inventory_pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: inventory-app
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://inventory-db:5432/${DB_NAME}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
    depends_on:
      - inventory-db

volumes:
  inventory_pg_data:
