# 1. Etapa de compilación
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copiamos específicamente el contenido de la carpeta backend
COPY backend/pom.xml .
COPY backend/src ./src

# Compilamos
RUN mvn clean package -DskipTests

# 2. Etapa de ejecución
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copiamos el JAR generado en la etapa anterior
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]